[package]
name = "lockpipes"
version = "0.4.0"
authors = ["Chris Olstrom <chris@olstrom.com>"]
edition = "2018"
license = "MIT"
description = "a commitment-free alternative to sleep"

[dependencies]
nix = "^0.18.0" # SPDX-License-Identifier: MIT
